export interface Product {
  id: string;
  title: string;
  price: string;
  oldPrice?: string;
  discount?: string;
  image: string;
  gallery?: string[];
  description: string;
  features: string[];
  category: "conteneur" | "caravane" | "mobile-home" | "remorque";
  options?: string[];
  specs: Record<string, string | string[]>;
}

export const products: Product[] = [
  {
    id: "conteneur-imgk",
    title: "Nouveau conteneur rouge de 20 pieds à ouverture latérale",
    price: "2550 €",
    image: "/images/conteneur/imgk/WhatsApp Image 2026-05-15 at 11.29.03.jpeg",
    gallery: [
      "/images/conteneur/imgk/WhatsApp Image 2026-05-15 at 11.29.03.jpeg",
      "/images/conteneur/imgk/WhatsApp Image 2026-05-15 at 11.29.13.jpeg",
      "/images/conteneur/imgk/WhatsApp Image 2026-05-15 at 11.29.14.jpeg",
      "/images/conteneur/imgk/WhatsApp Image 2026-05-15 at 11.29.16.jpeg",
      "/images/conteneur/imgk/WhatsApp Image 2026-05-15 at 11.29.24.jpeg",
    ],
    description:
      "Conteneur maritime neuf de 6 mètres (20 pieds) à ouverture latérale totale par portes battantes. Accès complet par le côté et par les doubles portes arrière. Intérieur propre avec plancher en contreplaqué. Poids maximal supporté : 16 000 kg. Idéal pour le chargement et le déchargement rapides, les salons professionnels, les événements ou un usage commercial.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "3.600 kg",
      payload: "12.400 kg",
      material: "Acier Corten",
      status: "Neuf - Jamais utilisé",
      colors: "Rouge / RAL 3026",
    },
  },  {
    id: "conteneur-imgb",
    title:
      "Maison conteneur de 6 mètres, rouge bordeaux, avec salle de bain et cuisine",
    price: "3490 €",
    image:
     "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.29 (1).jpeg",
    gallery: [
      "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.18 (3).jpeg",
      "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.29 (1).jpeg",
      "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.30 (1).jpeg",
      "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.30 (2).jpeg",
      "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.30 (3).jpeg",
      "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.30.jpeg",
      "/images/conteneur/imgb/WhatsApp Image 2026-05-15 at 11.39.31.jpeg",
    ],
    description:
      "Conteneur maritime de 6 mètres transformé en habitation complète, de couleur rouge bordeaux avec bardage horizontal imitation bois. Elle comprend une salle de bain avec douche en verre trempé, WC et lavabo ; une cuisine avec placards blancs et crédence en mosaïque ; climatisation réversible ; fenêtres en aluminium blanc ; et une porte d'entrée blanche avec luminaire extérieur. L'intérieur se caractérise par des murs blancs, un plafond en PVC et un sol carrelé. Idéal comme maison compacte, studio indépendant ou hébergement rural.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "2.800 kg",
      payload: "—",
      material: "clôture en acier Corten et en bois",
      status: "Transformé - Nouveau",
      colors: "Rouge bordeaux / RAL 3011",
    },
  },
  {
    id: "conteneur-imgc",
    title:
      "Maison écologique en conteneur de 40 pieds avec cuisine complète et chambres",
    price: "6990 €",
    image: "/images/conteneur/imgc/WhatsApp Image 2026-05-15 at 11.39.20.jpeg",
    gallery: [
      "/images/conteneur/imgc/WhatsApp Image 2026-05-15 at 11.39.18 (1).jpeg",
      "/images/conteneur/imgc/WhatsApp Image 2026-05-15 at 11.39.18 (2).jpeg",
      "/images/conteneur/imgc/WhatsApp Image 2026-05-15 at 11.39.18.jpeg",
      "/images/conteneur/imgc/WhatsApp Image 2026-05-15 at 11.39.19 (1).jpeg",
      "/images/conteneur/imgc/WhatsApp Image 2026-05-15 at 11.39.19.jpeg",
      "/images/conteneur/imgc/WhatsApp Image 2026-05-15 at 11.39.20.jpeg",
    ],
    description:
      "Contenedor marítimo de 40 pies transformado en vivienda completa color verde. Intérieur haut de gamme avec cuisine équipée (meubles blancs, plan de travail granit, crédence marbre, placards hauts), salon lumineux avec baies vitrées coulissantes, chambres séparées avec portes en bois foncé et sol en carrelage imitation bois. Plafond en PVC blanc, éclairage encastré, climatisation et installation électrique complète. Fenêtres en aluminium blanc. Ideal como vivienda permanente o alojamiento rural.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "12.19m × 2.44m × 2.59m",
      weight: "4.200 kg",
      payload: "—",
      material: "acier corten",
      status: "Transformé - Nouveau",
      colors: "Vert / RAL 6032",
    },
  },
  {
    id: "conteneur-imgd",
    title:
      "Tiny House de 6 mètres (20 pieds) noire et rouge sur pilotis avec cuisine et terrasse",
    price: "5490€",
    image:
      "/images/conteneur/imgd/WhatsApp Image 2026-05-15 at 11.39.04 (1).jpeg",
    gallery: [
      "/images/conteneur/imgd/WhatsApp Image 2026-05-15 at 11.39.04 (1).jpeg",
      "/images/conteneur/imgd/WhatsApp Image 2026-05-15 at 11.39.04 (2).jpeg",
      
      "/images/conteneur/imgd/WhatsApp Image 2026-05-15 at 11.39.05.jpeg",
      "/images/conteneur/imgd/WhatsApp Image 2026-05-15 at 11.39.08 (1).jpeg",
      "/images/conteneur/imgd/WhatsApp Image 2026-05-15 at 11.39.08.jpeg",
    ],
    description:
      "Tiny house de 20 pies sobre pilotis de hormigón con revestimiento en chapa ondulada negra y acentos en madera roja. Techo inclinado con alero. Interior luminoso con paredes blancas, suelo laminado parquet, cocina equipada con encimera de granito, fregadero y campana extractora. Baie vitrée coulissante panorámique, terrasse avec garde-corps métallique et ventanas en aluminio negro. Ideal como casa rural, refugio de montaña, estudio o alojamiento turístico.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.89m",
      weight: "2.800 kg",
      payload: "—",
      material: "Acier + tôle ondulée",
      status: "Transformé - Nouveau",
      colors: "Noir / RAL 9005, Rouge / RAL 3020",
    },
  },
  {
    id: "conteneur-imge",
    title: "Conteneur neuf de 3 mètres avec porte sectionnelle",
    price: "1390 €",
    image:
      "/images/conteneur/imge/WhatsApp Image 2026-05-15 at 11.27.24 (1).jpeg",
    gallery: [
      "/images/conteneur/imge/WhatsApp Image 2026-05-15 at 11.27.24 (1).jpeg",
      
      "/images/conteneur/imge/WhatsApp Image 2026-05-15 at 11.27.24.jpeg",
      "/images/conteneur/imge/WhatsApp Image 2026-05-15 at 11.27.25 (1).jpeg",
      "/images/conteneur/imge/WhatsApp Image 2026-05-15 at 11.27.25 (2).jpeg",
      "/images/conteneur/imge/WhatsApp Image 2026-05-15 at 11.27.25.jpeg",
    ],
    description:
      "Conteneur maritime neuf de 3 mètres avec portes sectionnelles à ouverture facile. Finition beige, structure renforcée avec points d'ancrage ISO. Intérieur propre avec plancher en contreplaqué. Idéal pour le stockage dans les petits espaces, les jardins ou un usage professionnel.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "2.99m × 2.44m × 2.59m",
      weight: "1.350 kg",
      payload: "10.150 kg",
      material: "Acier Corten",
      status: "Neuf - IICL5",
      colors: "Beige / RAL 1001",
    },
  },
  {
    id: "conteneur-imgf",
    title: "Conteneur d'occasion de 10 pieds avec double porte",
    price: "890 €",
    image:
      "/images/conteneur/imgf/WhatsApp Image 2026-05-15 at 11.27.34 (1).jpeg",
    gallery: [
      "/images/conteneur/imgf/WhatsApp Image 2026-05-15 at 11.27.34 (1).jpeg",
     
      "/images/conteneur/imgf/WhatsApp Image 2026-05-15 at 11.27.36.jpeg",
      "/images/conteneur/imgf/WhatsApp Image 2026-05-15 at 11.27.37 (1).jpeg",
      "/images/conteneur/imgf/WhatsApp Image 2026-05-15 at 11.27.37.jpeg",
      "/images/conteneur/imgf/WhatsApp Image 2026-05-15 at 11.27.38 (2).jpeg",
      "/images/conteneur/imgf/WhatsApp Image 2026-05-15 at 11.27.38.jpeg",
    ],
    description:
      "Conteneur maritime d'occasion de 3 mètres (10 pieds) avec double porte de sécurité et barres de verrouillage renforcées. Construction robuste en acier Corten gris. Idéal pour le stockage sur chantier, le jardinage ou les applications industrielles. Points d'ancrage ISO aux angles.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "2.99m × 2.44m × 2.59m",
      weight: "1.350 kg",
      payload: "10.150 kg",
      material: "Acier Corten",
      status: "Neuf - IICL5",
      colors: "Beige / RAL 1001",
    },
  },
  {
    id: "conteneur-imgg",
    title: "Conteneur rouge neuf de 3 mètres avec double porte",
    price: "1290 €",
    image:
      "/images/conteneur/imgg/WhatsApp Image 2026-05-15 at 11.27.56 (1).jpeg",
    gallery: [
      
      "/images/conteneur/imgg/WhatsApp Image 2026-05-15 at 11.27.48.jpeg",
      "/images/conteneur/imgg/WhatsApp Image 2026-05-15 at 11.27.50.jpeg",
      "/images/conteneur/imgg/WhatsApp Image 2026-05-15 at 11.27.56 (1).jpeg",
      "/images/conteneur/imgg/WhatsApp Image 2026-05-15 at 11.27.56.jpeg",
    ],
    description:
      " Conteneur maritime rouge neuf de 3 mètres (10 pieds) avec double porte de sécurité et barres de verrouillage renforcées. Intérieur propre avec parois ondulées et plancher en contreplaqué. Structure robuste avec points d'ancrage ISO. Idéal pour le stockage professionnel, les chantiers ou les jardins.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "2.99m × 2.44m × 2.59m",
      weight: "825 kg",
      payload: "6.500 kg",
      material: "Acier Corten",
      status: "Neuf - Jamais utilisé",
      colors: "Rouge / RAL 3020",
    },
  },
  {
    id: "conteneur-imgh",
    title: "Conteneur de 20 pieds, nouveau camouflage militaire",
    price: "1950 €",
    image:
      "/images/conteneur/imgh/WhatsApp Image 2026-05-15 at 11.28.00 (1).jpeg",
    gallery: [
      "/images/conteneur/imgh/WhatsApp Image 2026-05-15 at 11.28.00 (1).jpeg",
      
      "/images/conteneur/imgh/WhatsApp Image 2026-05-15 at 11.28.06 (1).jpeg",
      "/images/conteneur/imgh/WhatsApp Image 2026-05-15 at 11.28.06 (2).jpeg",
      "/images/conteneur/imgh/WhatsApp Image 2026-05-15 at 11.28.06 (3).jpeg",
      "/images/conteneur/imgh/WhatsApp Image 2026-05-15 at 11.28.06.jpeg",
    ],
    description:
      "Conteneur maritime neuf de 6 mètres (20 pieds) avec peinture camouflage militaire exclusive. Portes doubles avec barres de verrouillage renforcées. Intérieur spacieux avec plancher en contreplaqué. Points d'ancrage ISO aux quatre coins. Idéal pour le stockage, un usage militaire, la chasse ou les environnements ruraux.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "2.200  kg",
      payload: "21.800 kg",
      material: "Acier Corten",
      status: "Neuf - Jamais utilisé",
      colors: "Camouflage militaire",
    },
  },
  {
    id: "conteneur-imgi",
    title: "Conteneur neuf de 20 pieds, vert militaire",
    price: "1890 €",
    image: "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.13.jpeg",
    gallery: [
      "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.13.jpeg",
      "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.14 (1).jpeg",
      "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.14.jpeg",
      "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.15 (1).jpeg",
      "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.15.jpeg",
      "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.16 (1).jpeg",
      "/images/conteneur/imgi/WhatsApp Image 2026-05-15 at 11.28.16.jpeg",
    ],
    description:
      "Conteneur maritime neuf de 6 mètres (20 pieds) vert militaire. Portes doubles avec barres de verrouillage renforcées et joints étanches. Intérieur propre avec plancher en contreplaqué. Charge utile de 28 280 kg. Points d'arrimage ISO. Idéal pour le stockage professionnel, agricole ou militaire.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "2.200  kg",
      payload: "28.280 kg",
      material: "Acier Corten",
      status: "Neuf - Jamais utilisé",
      colors: "Vert militaire / RAL 6014",
    },
  },
  {
    id: "conteneur-imgj",
    title: "Conteneur d'occasion de 40 pieds avec double porte",
    price: "1400 €",
    image: "/images/conteneur/imgj/WhatsApp Image 2026-05-15 at 11.28.25.jpeg",
    gallery: [
      "/images/conteneur/imgj/WhatsApp Image 2026-05-15 at 11.28.25.jpeg",
      "/images/conteneur/imgj/WhatsApp Image 2026-05-15 at 11.28.27.jpeg",
      "/images/conteneur/imgj/WhatsApp Image 2026-05-15 at 11.28.28 (1).jpeg",
      "/images/conteneur/imgj/WhatsApp Image 2026-05-15 at 11.28.28 (2).jpeg",
      "/images/conteneur/imgj/WhatsApp Image 2026-05-15 at 11.28.28 (3).jpeg",
      "/images/conteneur/imgj/WhatsApp Image 2026-05-15 at 11.28.28.jpeg",
    ],
    description:
      "Conteneur maritime d'occasion de 40 pieds (42G1) avec double porte de sécurité et barres de verrouillage renforcées. Grande capacité de stockage de 67 m³ de volume intérieur. Construction robuste en acier Corten. Idéal pour le stockage industriel, la logistique ou l'agriculture. Disponible en plusieurs couleurs, selon les stocks.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "12.19m × 2.44m × 2.59m",
      weight: "3.750 kg",
      payload: "26.730 kg",
      material: "Acier Corten",
      status: "Occasion - Bon état",
      colors: "Marron / Rouge Rouille",
    },
  },
  {
    id: "conteneur-imgl",
    title: "Conteneur bleu neuf de 20 pieds avec double porte",
    price: "1790 €",
    image:
      "/images/conteneur/imgl/WhatsApp Image 2026-05-15 at 11.29.40 (1).jpeg",
    gallery: [
      "/images/conteneur/imgl/WhatsApp Image 2026-05-15 at 11.29.40 (1).jpeg",
      
      "/images/conteneur/imgl/WhatsApp Image 2026-05-15 at 11.29.41.jpeg",
      "/images/conteneur/imgl/WhatsApp Image 2026-05-15 at 11.29.42 (1).jpeg",
      "/images/conteneur/imgl/WhatsApp Image 2026-05-15 at 11.29.42.jpeg",
      "/images/conteneur/imgl/WhatsApp Image 2026-05-15 at 11.29.43.jpeg",
    ],
    description:
      "Conteneur maritime neuf de 6 mètres (20 pieds) bleu, équipé de doubles portes de sécurité et de barres de verrouillage renforcées. Intérieur propre avec plancher en contreplaqué. Capacité de 33,2 m³. Points d'ancrage ISO aux quatre coins. Idéal pour le stockage professionnel, la logistique ou un usage industriel.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "2.050 kg",
      payload: "28.430 kg",
      material: "Acier Corten",
      status: "Neuf - Jamais utilisé",
      colors: "Bleu / RAL 5010",
    },
  },
  {
    id: "conteneur-imgm",
    title:
      "Maison blanche aménagée dans un conteneur de 6 mètres avec baie vitrée",
    price: "1640 €",
    image: "/images/conteneur/imgm/WhatsApp Image 2026-05-15 at 11.38.10.jpeg",
    gallery: [
      "/images/conteneur/imgm/WhatsApp Image 2026-05-15 at 11.38.10 (1).jpeg",
      "/images/conteneur/imgm/WhatsApp Image 2026-05-15 at 11.38.10 (2).jpeg",
      "/images/conteneur/imgm/WhatsApp Image 2026-05-15 at 11.38.10.jpeg",
      "/images/conteneur/imgm/WhatsApp Image 2026-05-15 at 11.38.11 (1).jpeg",
      "/images/conteneur/imgm/WhatsApp Image 2026-05-15 at 11.38.11 (2).jpeg",
      "/images/conteneur/imgm/WhatsApp Image 2026-05-15 at 11.38.11.jpeg",
    ],
    description:
      "Maison blanche aménagée dans un conteneur de 6 mètres avec baie vitrée",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "2.700 kg",
      payload: "-",
      material: "Acier Corten",
      status: "Transformé - Remis à neuf",
      colors: "Blanc / RAL 9010",
    },
  },
  {
    id: "conteneur-imgn",
    title: "Conteneur de 20 pieds transformé avec porte enroulable",
    price: "2100 €",
    image:
      "/images/conteneur/imgn/WhatsApp Image 2026-05-15 at 11.29.48 (1).jpeg",
    gallery: [
      "/images/conteneur/imgn/WhatsApp Image 2026-05-15 at 11.29.48 (1).jpeg",
      "/images/conteneur/imgn/WhatsApp Image 2026-05-15 at 11.29.48 (2).jpeg",
      
      "/images/conteneur/imgn/WhatsApp Image 2026-05-15 at 11.29.49 (1).jpeg",
      "/images/conteneur/imgn/WhatsApp Image 2026-05-15 at 11.29.49.jpeg",
    ],
    description:
      "Solution de conteneur modulaire polyvalente, idéale pour le stockage, le bureau ou l'habitat temporaire. Modèle robuste et personnalisable.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "2.300 kg",
      payload: "25.000 kg",
      material: "Acier Corten",
      status: "Transformé - Remis à neuf",
      colors: "Bleu / RAL 5010",
    },
  },
  {
    id: "conteneur-imgo",
    title: "Nouveau conteneur de bureau climatisé blanc/bleu de 20 pieds",
    price: "2290 €",
    image:
      "/images/conteneur/imgo/WhatsApp Image 2026-05-15 at 11.37.49 (1).jpeg",
    gallery: [
      "/images/conteneur/imgo/WhatsApp Image 2026-05-15 at 11.37.49 (1).jpeg",
      "/images/conteneur/imgo/WhatsApp Image 2026-05-15 at 11.37.49 (2).jpeg",
      
      "/images/conteneur/imgo/WhatsApp Image 2026-05-15 at 11.37.50.jpeg",
    ],
    description:
      "Nouveau module de bureau de 6 mètres (20 pieds) avec une structure bleue RAL 5010 et des panneaux sandwich blancs isolés. Équipé de la climatisation, de fenêtres avec stores enrouleurs, d'une porte d'accès avec serrure de sécurité et d'un précâblage électrique. Idéal comme bureau de chantier, bureau temporaire, salle de réunion ou poste de contrôle.",
    features: [
      "Structure en acier galvanisé",
      "Isolation thermique performante",
      "Installation rapide",
      "Personnalisable",
    ],
    category: "conteneur",
    specs: {
      dimensions: "6.06m × 2.44m × 2.59m",
      weight: "2.300 kg",
      payload: "25.000 kg",
      material: "Acier Corten",
      status: "Transformé - Remis à neuf",
      colors: "Blanc/Bleu / RAL 5010",
    },
  },

  {
    id: "caravane-imagb",
    title: "Montre Dethleffs Trend T7057 DBM d'occasion",
    price: "12000 €",
    image:
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.56 (1).jpeg",
    gallery: [
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.56 (1).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.56 (2).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.56 (6).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.56 (7).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.56.jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.57 (1).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.57 (2).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.57 (3).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.57.jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.58 (1).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.58 (2).jpeg",
      "/images/caravane/imagb/WhatsApp Image 2026-05-16 at 01.40.58.jpeg",
    ],

    description:
      "Le Sunlight 540V est un fourgon aménagé compact avec salon arrière, offrant un espace de vie convivial et fonctionnel, idéal pour ceux qui recherchent un véritable logement sur roues entièrement équipé.\n\nLe véhicule est basé sur un Fiat Ducato 2.2L de 103 kW (140 ch) avec transmission manuelle et traction avant. Son réservoir de carburant de 60 L assure une bonne autonomie pour les longs trajets. Il est équipé de pneus hiver M+S Camping.\n\nCôté sécurité et aide à la conduite, il dispose du contrôle électronique de stabilité (ESC), de l’antipatinage (ASR), de l’aide au démarrage en côte (Hill Holder), de l’assistant de vent latéral (CWA), du contrôle de stabilité de remorque, du freinage post-collision (PCB), de freins à disque, d’un stabilisateur sur les deux essieux, de la direction assistée, de phares réglables en hauteur, d’un antidémarrage, de ceintures de sécurité 3 points et du système Traction+ avec Hill Descent.\n\nLe confort de conduite est assuré par des sièges conducteur et passager pivotants avec soutien lombaire, accoudoirs et réglages en hauteur et inclinaison, ainsi que des airbags intégrés. Le véhicule inclut également un kit anti-crevaison Fix & Go.\n\nL’équipement de cabine comprend un ordinateur de bord avec température extérieure, des vitres électriques, une fermeture centralisée, une préinstallation radio avec antenne DAB, des rétroviseurs électriques et chauffants, un régulateur de vitesse, un port USB, un volant multifonction, un système Start & Stop avec booster et un porte-gobelets central.\n\nLa cuisine est entièrement équipée avec deux feux gaz à allumage électrique, un réfrigérateur à compression de 64 L, trois tiroirs avec fermeture servo-soft, un couvercle en verre, une barre multifonction avec crochets, un plan de travail rabattable et un éclairage LED. Le réservoir d’eau propre est de 100 L et celui des eaux usées de 90 L.\n\nLa salle de bain comprend un WC fixe, une douche spacieuse, un lavabo rabattable, un placard avec étagères et une surface de rangement pratique.\n\nLe chauffage est assuré par un système Combi 4 Diesel avec une bouteille de gaz de 2,75 kg.\n\nL’habitacle propose un salon arrière avec double banquette et table extractible, séparé de la cabine par une cloison thermo-isolante. De nombreux espaces de rangement sont disponibles : placards, étagères, compartiments dans les portes, rangement au-dessus de la cabine et garage arrière avec anneaux de fixation. Il inclut également une table de camping multifonction et une moustiquaire de porte.\n\nLe couchage se fait via un lit en toit relevable accessible par une échelle fixe, avec un matelas de haute qualité.\n\nLes fenêtres sont à double vitrage avec moustiquaires et stores occultants. Les portes arrière disposent de fenêtres ouvrantes avec occultants.\n\nCôté technologie, le véhicule est équipé d’une batterie AGM de 95 Ah sans entretien avec chargeur 18 A, de prises 3 x 230V, 1 USB et d’une prise extérieure CEE 230V. Un panneau de contrôle permet de surveiller les niveaux de batterie et des réservoirs.\n\nL’éclairage intérieur est entièrement en LED avec lampes de lecture réglables et éclairage dans le salon et la salle de bain.\n\nEnfin, le véhicule dispose d’un habillage extérieur Vanlife et d’un store extérieur noir.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      motorization: "Citroën 165 ch",
      placesToVisit: "5",
      sleepingSpaces: "5",
      totalLength: "741",
      externalWidth: "233",
      externalHeight: "290",
      frontBedDimensions: "200 x 140",
      rearBedDimensions: "190 x 150",
    },
  },
  {
    id: "caravane-imga",
    title: "Camping-car SUNLIGHT 540V",
    price: "11000 €",
    image: "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.41.56.jpeg",
    gallery: [
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.41.56.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.41.57.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.09 (1).jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.09.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.10 (1).jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.10.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.11 (1).jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.11.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.12 (1).jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.18 (1).jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.18.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.19.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.21 (1).jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.21.jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.22 (1).jpeg",
      "/images/caravane/imga/WhatsApp Image 2026-05-16 at 06.42.22.jpeg",
    ],

    description:
      "Le Sunlight 540V est un fourgon aménagé compact avec salon arrière, offrant un espace de vie convivial et fonctionnel, idéal pour ceux qui recherchent un véritable logement sur roues entièrement équipé.\n\nLe véhicule est basé sur un Fiat Ducato 2.2L de 103 kW (140 ch) avec transmission manuelle et traction avant. Son réservoir de carburant de 60 L assure une bonne autonomie pour les longs trajets. Il est équipé de pneus hiver M+S Camping.\n\nCôté sécurité et aide à la conduite, il dispose du contrôle électronique de stabilité (ESC), de l’antipatinage (ASR), de l’aide au démarrage en côte (Hill Holder), de l’assistant de vent latéral (CWA), du contrôle de stabilité de remorque, du freinage post-collision (PCB), de freins à disque, d’un stabilisateur sur les deux essieux, de la direction assistée, de phares réglables en hauteur, d’un antidémarrage, de ceintures de sécurité 3 points et du système Traction+ avec Hill Descent.\n\nLe confort de conduite est assuré par des sièges conducteur et passager pivotants avec soutien lombaire, accoudoirs et réglages en hauteur et inclinaison, ainsi que des airbags intégrés. Le véhicule inclut également un kit anti-crevaison Fix & Go.\n\nL’équipement de cabine comprend un ordinateur de bord avec température extérieure, des vitres électriques, une fermeture centralisée, une préinstallation radio avec antenne DAB, des rétroviseurs électriques et chauffants, un régulateur de vitesse, un port USB, un volant multifonction, un système Start & Stop avec booster et un porte-gobelets central.\n\nLa cuisine est entièrement équipée avec deux feux gaz à allumage électrique, un réfrigérateur à compression de 64 L, trois tiroirs avec fermeture servo-soft, un couvercle en verre, une barre multifonction avec crochets, un plan de travail rabattable et un éclairage LED. Le réservoir d’eau propre est de 100 L et celui des eaux usées de 90 L.\n\nLa salle de bain comprend un WC fixe, une douche spacieuse, un lavabo rabattable, un placard avec étagères et une surface de rangement pratique.\n\nLe chauffage est assuré par un système Combi 4 Diesel avec une bouteille de gaz de 2,75 kg.\n\nL’habitacle propose un salon arrière avec double banquette et table extractible, séparé de la cabine par une cloison thermo-isolante. De nombreux espaces de rangement sont disponibles : placards, étagères, compartiments dans les portes, rangement au-dessus de la cabine et garage arrière avec anneaux de fixation. Il inclut également une table de camping multifonction et une moustiquaire de porte.\n\nLe couchage se fait via un lit en toit relevable accessible par une échelle fixe, avec un matelas de haute qualité.\n\nLes fenêtres sont à double vitrage avec moustiquaires et stores occultants. Les portes arrière disposent de fenêtres ouvrantes avec occultants.\n\nCôté technologie, le véhicule est équipé d’une batterie AGM de 95 Ah sans entretien avec chargeur 18 A, de prises 3 x 230V, 1 USB et d’une prise extérieure CEE 230V. Un panneau de contrôle permet de surveiller les niveaux de batterie et des réservoirs.\n\nL’éclairage intérieur est entièrement en LED avec lampes de lecture réglables et éclairage dans le salon et la salle de bain.\n\nEnfin, le véhicule dispose d’un habillage extérieur Vanlife et d’un store extérieur noir.",

    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      marqueVehicule: "SUNLIGHT",
      modeleVehicule: "540 V",
      typeVehicule: "Fourgon aménagé",
      placesCouchage: "4 places",
      placesVoyage: "2 places",
      placesRepas: "4 places",
      permisConduire: "B",
      poidsMaxAutorise: "3500 kg",
      longueur: "541 cm",
      largeur: "205 cm",
      hauteur: "281 cm",
      motorisation: "Fiat 2.2L 103 kW 140 ch",
      hauteurInterieure: "190 cm",
      placesAssises: "2",
      chassisMotorisationPuissance: "Fiat Ducato / 2.2L / 103 kW (140 ch)",
      masseEnOrdreDeMarche: "2829 kg",
      masseEquipementsOptionnels: "522 kg",
      masseMaximaleAutorisee: "3500 kg",
      chargeRemorquablePente12: "2500 / 750 kg",
      pneumatiques: "225/75 R 16 CP",
      empattement: "345 cm",
      dimensionsLitToit: "206 x 143 cm",
      refrigerateur: "64 L",
      reservoirEau: "100 / 20 / 90",
      chauffage: "Combi 4 Diesel",
      gaz: "1 x 2,75 kg",
      kilometrage: "56 203 km",
    },
  },
  {
    id: "caravane-imgc",
    title: "Weinsberg CaraOne 390 QD",
    price: "2700 €",
    image:
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.32 (1).jpeg",
    gallery: [
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.32 (1).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.32.jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.33 (1).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.33 (2).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.33 (3).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.33 (4).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.33 (5).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.33.jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.34 (1).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.34 (2).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.34 (3).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.34 (4).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.34.jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.35 (1).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.35 (2).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.35 (3).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.35 (4).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.35 (5).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.35 (6).jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.35.jpeg",
      "/images/caravane/imgc/WhatsApp Image 2026-05-16 at 01.41.36.jpeg",
    ],

    description:
      "La Weinsberg CaraOne 390 QD est une caravane compacte et pratique, idéale pour voyager en couple ou en famille. Avec une longueur totale de 5,93 mètres et un poids à vide de 914 kg, elle est facile à tracter et à manœuvrer sur la route.\n\nL’intérieur est bien optimisé et propose un lit double fixe à l’avant ainsi qu’un espace repas à l’arrière transformable en couchage double, permettant d’accueillir jusqu’à quatre personnes.\n\nLa cuisine est entièrement équipée avec un réfrigérateur, une plaque de cuisson au gaz et un évier, offrant tout le nécessaire pour préparer des repas en toute simplicité pendant le voyage.\n\nLa caravane dispose également d’un espace sanitaire comprenant un WC et un lavabo.\n\nLa CaraOne 390 QD se distingue par son excellent rapport praticité/prix, avec un aménagement intelligent qui maximise l’espace disponible et garantit un confort de voyage agréable et fonctionnel.",

    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      longueurTotaleAvecFleche: "593 cm",
      longueurInterieure: "402 cm",
      largeurTotaleInterieure: "220 / 204 cm",
      hauteurTotaleInterieure: "257 / 196 cm",
      perimetreAuvent: "855 cm",
      masseReelleVehicule: "914 kg",
      poidsMaxAutoriseTechnique: "1200 / 1350 kg",
      chargeUtile: "286 kg",
      pneumatiques: "195 / 70 R 14",
      jantes: "5 1/2 J x 14",
      placesNuit: "4",
      couchagesMax: "4",
      dimensionsLitAvant: "196 x 140 / 128 cm",
      dimensionsLitArriere: "187 x 117 / 88 cm",
      dimensionsPorte: "60 x 181 cm",
      refrigerateur: "98 L",
      reservoirEauPropre: "15 L",
      prises230V: "2",
    },
  },
  {
    id: "caravane-imgd",
    title: "Château 350 Carats – 750 kg",
    price: "2600 €",
    image:
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.46 (2).jpeg",
    gallery: [
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.46 (2).jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.46 (3).jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.47 (1).jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.47 (2).jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.47 (3).jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.47 (4).jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.47.jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.48 (1).jpeg",
      "/images/caravane/imgd/WhatsApp Image 2026-05-16 at 01.41.48.jpeg",
    ],
    description:
      "Cette caravane compacte et fonctionnelle affiche un poids à vide de 640 kg, un PTAC de 750 kg et une charge utile de 260 kg, ce qui la rend facile à tracter et adaptée à de nombreux véhicules.\n\nÀ l’avant, elle dispose d’une banquette transversale convertible en salon deux places, idéale pour les moments de détente. À l’arrière, des banquettes deux places peuvent être transformées en lit simple, offrant une configuration modulable selon les besoins.\n\nLa cuisine centrale est bien équipée avec un réfrigérateur incluant un compartiment congélateur de 65 litres, un évier en inox et une plaque de cuisson à gaz à trois feux avec couvercle en bois, permettant de cuisiner confortablement en déplacement.\n\nUn auvent est inclus en option.\n\nLes auvents, systèmes de déplacement, antennes, téléviseurs et autres accessoires ou options d’occasion ne sont pas inclus dans le contrat de vente ; par conséquent, aucune garantie ni responsabilité ne s’applique à ces éléments.\n\nTous les équipements sont présentés en état de fonctionnement lors de la vente, avec une explication du système de gaz. Un contrôle technique complet (DEKRA, TÜV Nord) ainsi qu’un test de gaz récents ont été effectués.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      nombreLits: "3",
      longueurTotale: "5070 mm",
      largeurTotale: "2100 mm",
      hauteurTotale: "2530 mm",
      nombreEssieux: "1",
      poidsTotal: "750 kg",
    },
  },
  {
    id: "caravane-imge",
    title: "Laika Kosmo L 319",
    price: "24000 €",
    image: "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.20.jpeg",
    gallery: [
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.20.jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.21 (1).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.21 (3).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.21.jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.22 (1).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.22 (3).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.22 (4).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.22 (5).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.22.jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.23 (1).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.23 (2).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.23 (3).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.23.jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.24 (1).jpeg",
      "/images/caravane/imge/WhatsApp Image 2026-05-16 at 01.44.24.jpeg",
    ],
    description:
      "Ce camping-car modèle L 319 de l’année 2024 est un véhicule moderne, confortable et parfaitement équipé pour les voyages en couple ou en famille. Il repose sur un châssis Fiat Ducato 2.2L MultiJet développant 103 kW (140 ch), associé à une boîte de vitesses automatique pour une conduite fluide et agréable. Son PTAC est de 3500 kg.\n\nL’aménagement intérieur propose des couchages sous forme de lits simples, offrant confort et praticité. La sellerie Firenze en similicuir beige apporte une touche élégante et chaleureuse à l’espace de vie.\n\nLe Pack Châssis inclut des commandes radio au volant, une antenne DAB, une préinstallation pour autoradio avec haut-parleurs en cabine, le système Traction+ ainsi que le contrôle de descente.\n\nLe Pack Design Châssis ajoute des finitions haut de gamme avec une calandre au contour noir, un volant et un pommeau en cuir véritable, des phares avec contour noir et des inserts décoratifs Techno-Trim sur le tableau de bord.\n\nLe Pack Confort Kosmo L renforce le bien-être à bord avec une cabine de douche en bois, un tapis de cabine, une hotte aspirante, un réservoir d’eaux usées isolé et chauffé, un toit panoramique T-top avec Skyview rabattable, des parois de chambre en similicuir, des rangements modulables dans la cuisine et une porte Premium XL avec télécommande, moustiquaire, store occultant et vérins à gaz. Il inclut également la préinstallation pour caméra de recul et des housses de sièges assorties à l’espace de vie.\n\nCe véhicule est également équipé de jantes alliage 16 pouces d’origine Fiat sur châssis lourd, d’un chauffage performant Combi 6 E, de feux antibrouillard avec fonction éclairage en virage et d’un frein de stationnement électrique.\n\nDes équipements supplémentaires viennent compléter l’ensemble, notamment la transformation du siège en couchage (lit simple), un four à gaz ainsi qu’un revêtement d’assise et de dossier en similicuir Firenze beige.\n\nCe camping-car combine parfaitement technologie, confort et design pour offrir une expérience de voyage haut de gamme.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      nombreCouchages: "4",
      placesVoyage: "4",
      carburant: "Diesel",
      transmission: "Automatique",
      couleur: "Blanc",
      longueurTotale: "6950 mm",
      largeurTotale: "2320 mm",
      hauteurTotale: "2950 mm",
      nombreEssieux: "2",
      modele: "L 319",
      poidsTotal: "3500 kg",
      equipementsPrincipaux: ["Verrouillage centralisé", "Salle de bains"],
    },
  },
  {
    id: "caravane-imgf",
    title: "Sun Living S 70SL d'occasion",
    price: "21000 €",
    image: "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.42.49.jpeg",
    gallery: [
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.42.49.jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.42.56.jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.00.jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.01 (1).jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.01 (2).jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.01 (3).jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.02 (1).jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.02 (2).jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.02.jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.03 (1).jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.04.jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.05.jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.08 (1).jpeg",
      "/images/caravane/imgf/WhatsApp Image 2026-05-16 at 06.43.08.jpeg",
    ],
    description:
      "Ce camping-car est équipé de jantes alliage 16 pouces, d’un volant aspect cuir, de pare-chocs avant peints et de feux antibrouillard, offrant un design moderne et élégant.\n\nParmi les équipements optionnels, on retrouve une préparation pour radio numérique DAB avec volant multifonctions, un chargeur de batterie, un organiseur, un toit panoramique à l’avant, un système de verrouillage centralisé avec vitres et poubelle intégrée dans l’habitacle, ainsi qu’un lanterneau panoramique dans l’espace de vie.\n\nL’équipement standard comprend une carrosserie blanche et une sellerie Gavin, ainsi que de nombreux systèmes de sécurité et d’assistance : airbags conducteur et passager, ABS, ASR, ESP, EBD, HBA et LAC, fixations Isofix pour siège enfant, aide au stationnement arrière et climatisation cabine.\n\nLe véhicule est également doté de rétroviseurs électriques et chauffants, de vitres électriques, d’un verrouillage centralisé radiofréquence, d’un régulateur de vitesse et de sièges cabine confort réglables en hauteur avec accoudoirs.\n\nCôté performance et conformité, il respecte la norme Euro 6e et inclut un kit de réparation de pneus.\n\nLe confort à bord est assuré par une batterie auxiliaire AGM 100 Ah, une prise 230 V / 12 V dans le garage, un détendeur de sécurité gaz MonoControl CS avec filtre, ainsi qu’un WC à cassette avec chasse d’eau électrique.\n\nLe véhicule dispose également d’un store occultant cabine, d’un lanterneau 40 x 40 cm dans l’espace de vie, d’une moustiquaire sur la porte cellule et d’un encadrement de fenêtre dans la cuisine.\n\nPour le couchage, il est équipé d’un matelas en mousse à froid dans le lit fixe, de coussins décoratifs et d’un lit rabattable, offrant un espace de repos confortable et modulable.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",

    specs: {
      puissance: "103 kW (140,04 ch)",
      nombreCouchages: "5",
      carburant: "Diesel",
      typeTransmission: "Mécanique",
      longueurTotale: "6990 mm",
      largeurTotale: "2320 mm",
      hauteurTotale: "2890 mm",
      nombreEssieux: "2",
      annee: "2015",
      kilometrage: "31 796 km",
      poidsTotal: "3500 kg",
      equipements: [
        "ABS",
        "ESP",
        "Climatisation",
        "Verrouillage centralisé",
        "Salle de bains",
        "Filtre à particules",
      ],
    },
  },
  {
    id: "caravane-imgg",
    title: "Weinsberg CaraOne 390 QD 750 kg",
    price: "6000 €",
    image:
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.09 (1).jpeg",
    gallery: [
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.09 (1).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.10 (1).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.10 (3).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.10.jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.11.jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.12 (1).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.12 (2).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.12 (3).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.12 (4).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.12.jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.13 (1).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.13 (2).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.13.jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.14 (1).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.14 (2).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.14.jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.15 (1).jpeg",
      "/images/caravane/imgg/WhatsApp Image 2026-05-16 at 06.43.15.jpeg",
    ],

    description:
      "La caravane Weinsberg CaraOne 390 QD est compacte et pratique, idéale pour les couples ou les familles. Avec une longueur totale de 5,93 mètres et un poids à vide de 660 kg, elle est facile à tracter et à manœuvrer sur route.\n\nL’intérieur de la caravane comprend un lit double fixe à l’avant ainsi qu’une dînette convertible en lit double à l’arrière, permettant d’accueillir jusqu’à quatre personnes.\n\nLa cuisine est entièrement équipée avec un réfrigérateur, une plaque de cuisson au gaz et un évier, offrant tout le nécessaire pour préparer des repas en voyage.\n\nElle dispose également d’une salle de bain comprenant des toilettes et un lavabo.\n\nLa CaraOne 390 QD se distingue par son excellent rapport qualité-prix, avec une conception intelligente qui optimise l’espace disponible et garantit une expérience de voyage confortable et fonctionnelle.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      longueurTotaleAvecFlèche: "588 cm",
      longueurInterieure: "402 cm",
      largeurTotaleInterieure: "220 / 204 cm",
      hauteurTotaleInterieure: "257 / 196 cm",
      perimetreAvancement: "855 cm",
      masseReelle: "660 kg",
      poidsMaxAutorise: "750 kg",
      chargeUtile: "286 kg",
      pneus: "195/70 R 14",
      jantes: "5 1/2 J x 14",
      nombreCouchages: "4",
      couchagesMax: "4",
      dimensionsLitAvant: "196 x 140 / 128 cm",
      dimensionsLitArriere: "187 x 117 / 88 cm",
      porteEntree: "60 x 181 cm",
      refrigerateur: "98 L",
      reservoirEauPropre: "15 L",
      prises230V: "2",
    },
  },
  {
    id: "caravane-imgh",
    title: "Beachy 360 2024 d'occasion",
    price: "6000 €",
    image:
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.38 (1).jpeg",
    gallery: [
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.38 (1).jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.38.jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.39 (1).jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.39.jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.40 (1).jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.40 (2).jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.40.jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.46.jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.48.jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.49 (1).jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.49.jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.50 (1).jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.50 (2).jpeg",
      "/images/caravane/imgh/WhatsApp Image 2026-05-16 at 06.43.50.jpeg",
    ],
    description:
      "Beachy 360 2024 – Le compagnon idéal pour vos escapades spontanées.\n\nLa Beachy 360 est une caravane compacte, pratique et moderne, pensée pour accompagner toutes vos aventures. Son design contemporain et ses nombreuses options personnalisables en font un véhicule de loisirs à la fois fonctionnel et élégant, parfaitement adapté aux voyages spontanés.\n\nPrésentée par Go Loisirs Lehmann, fort de 50 ans d’expérience dans la vente de véhicules de loisirs en Alsace, cette caravane bénéficie d’un savoir-faire reconnu et d’une expertise solide dans le domaine du camping et du caravaning.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      categorie: "Caravane",
      typeCaravane: "Rigide",
      etat: "Neuf",
      annee: "2024",
      dimensions: "5,09 m x 2,17 m",
      longueur: "5,09 m",
      largeur: "2,17 m",
      hauteur: "2,68 m",
      ptac: "900 kg",
      poidsAVide: "757 kg",
      garantie: "24 mois",
      capaciteCouchage: "3 personnes (2 adultes, 1 enfant)",
      poidsMaxCharge: "900 kg",
      poidsAVideDetail: "733 kg (696-770)",
      litConvertibleDimensions: "2000 x 1800 mm",
      prises230V: "3",
    },
  },
  {
    id: "caravane-imgi",
    title: "CARAVANE CARPENTO 310 D'OCCASION",
    price: "5800 €",
    image: "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.07.jpeg",
    gallery: [
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.07.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.08.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.16.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.17.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.18 (1).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.18.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.19.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.21.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.22 (1).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.22.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.23 (1).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.23.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.24 (1).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.24 (2).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.24 (3).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.24.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.25 (1).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.25 (2).jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.25.jpeg",
      "/images/caravane/imgi/WhatsApp Image 2026-05-16 at 06.44.26.jpeg",
    ],
    description:
      "Caravane Carpento 310 d’occasion, idéale pour 2 personnes, avec un poids maximal autorisé de 750 kg. Compacte et fonctionnelle, elle offre un aménagement optimisé comprenant une pièce principale avec un lit convertible dans le séjour.\n\nLa cuisine est équipée d’une plaque de cuisson à un feu et d’un réfrigérateur, permettant de préparer facilement des repas en voyage.\n\nLa salle de bain dispose de toilettes chimiques et d’un receveur de douche en acrylique, assurant un confort de base complet.\n\nCôté équipement, elle est dotée d’un châssis AL-KO avec amortisseurs AL-KO, d’un revêtement de sol en PVC, de fenêtres équipées de moustiquaires et de stores, ainsi que d’une porte moustiquaire.\n\nL’éclairage intérieur est assuré par des LED. On retrouve également des toilettes chimiques Thetford et un réservoir d’eau propre pour plus d’autonomie.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      marque: "Carpento",
      modele: "310",
      typeEnvironnement: "Type 1",
      etat: "Occasion",
      siegesVoyage: "3",
      couchages: "2",
      agencement: "Lit convertible en salon",
      ptac: "750 kg",
      longueur: "4,40 m",
      largeur: "2,05 m",
      hauteur: "2,40 m",
    },
  },
  {
    id: "caravane-imgj",
    title: "Caravane T@B 320 d'occasion",
    price: "4200 €",
    image:
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.37 (1).jpeg",
    gallery: [
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.37 (1).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.37.jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.38 (1).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.38.jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.39 (1).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.39 (2).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.39.jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.40 (1).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.40 (2).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.40 (3).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.40 (4).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.40.jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.41 (3).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.41 (5).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.41 (6).jpeg",
      "/images/caravane/imgj/WhatsApp Image 2026-05-16 at 06.44.41.jpeg",
    ],
    description:
      "Caravane T@B 320 d’occasion de 2019, pouvant accueillir jusqu’à deux personnes. Son format compact en fait un véhicule idéal pour les voyages et les aventures en toute liberté.\n\nL’intérieur offre un espace de vie bien optimisé avec des rangements sous les sièges ainsi que dans des compartiments supérieurs. Le coin repas dispose d’une table pliante permettant de transformer facilement l’espace en un lit double confortable.\n\nLa cuisine est élégante et fonctionnelle, équipée d’une plaque de cuisson à deux feux, d’un évier en acier inoxydable, d’un petit réfrigérateur et de l’eau chaude.\n\nCôté équipement, elle dispose d’un châssis AL-KO, de fenêtres de toit avec moustiquaires et stores occultants, d’un coin repas modulable, d’une grande armoire et de compartiments de rangement supérieurs.\n\nUne garantie d’un an est incluse.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      marque: "T@B",
      modele: "320",
      annee: "2019",
      typeEnvironnement: "Type 1",
      siegesVoyage: "3",
      couchages: "2",
      agencement: "Lit convertible dans le salon",
      ptac: "750 kg",
      longueur: "5,17 m",
      largeur: "2,01 m",
      hauteur: "2,44 m",
      equipementsPrincipaux: [
        "Châssis AL-KO",
        "Salle à manger avec table pliante",
        "Réfrigérateur",
        "Grande armoire",
      ],
    },
  },
  {
    id: "caravane-imgk",
    title: "PÖSSL ROADY Vario 545 D'OCCASION",
    price: "9900 €",
    image: "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.09.jpeg",
    gallery: [
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.09.jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.39.jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.41 (1).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.41.jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.42 (2).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.42.jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.44 (1).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.44.jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.45 (1).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.45 (2).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.45 (3).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.45 (4).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.45.jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.46 (1).jpeg",
      "/images/caravane/imgk/WhatsApp Image 2026-05-16 at 06.45.46.jpeg",
    ],
    description:
      "Ce camping-car est équipé d’un moteur/châssis Citroën Jumper 2,2 L BlueHDi développant 103 kW (140 ch), associé à une transmission manuelle. Il affiche un kilométrage de 29 538 km et un poids brut autorisé de 3 500 kg.\n\nL’aménagement intérieur comprend un lit double ainsi que des lits superposés, offrant une capacité de couchage confortable. Le groupe de sièges est organisé en salon latéral, optimisant l’espace de vie.\n\nLe véhicule dispose d’un pack complet incluant ESP, ABS, ASR, aide au démarrage en côte, réservoir de carburant de 90 L, roue de secours taille normale, climatisation manuelle cabine, airbag passager, rétroviseurs électriques et chauffants, siège passager réglable en hauteur, sellerie cabine assortie à l’espace de vie, store occultant cabine rabattable, tableau de bord avec cerclages chromés et booster de charge 25 A.\n\nIl est également équipé de feux de jour à LED, régulateur de vitesse, Traction+, ainsi que de nombreuses assistances à la conduite : freinage d’urgence, alerte de franchissement de ligne, assistance feux de route, reconnaissance des panneaux de signalisation et capteurs de pluie et de luminosité.\n\nLe confort intérieur comprend un lit arrière avec matelas, une table avec rallonge pivotante, une batterie embarquée supplémentaire de 95 Ah, des prises 230 V et USB, une fenêtre supplémentaire dans le toit arrière, ainsi qu’un panneau de commande Truma CP Plus.\n\nLes fenêtres arrière des portes sont équipées de stores enrouleurs, et la toiture est réalisée en PRV avec peinture spécifique.\n\nLe véhicule dispose également d’un système de fermeture amortie pour la porte latérale coulissante, d’un marchepied rétractable Omnistep Slide Out, d’un kit d’hygiène, d’une caméra de recul, du système de sécurité HEO, d’un porte-vélos Busbiker, d’une télévision et d’une boule de remorquage amovible.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      kilometrage: "29 538 km",
      puissance: "103 kW (140,04 ch)",
      nombreCouchages: "4",
      carburant: "Diesel",
      typeTransmission: "Mécanique",
      premiereImmatriculation: "10/2021",
      longueurTotale: "5410 mm",
      largeurTotale: "2050 mm",
      hauteurTotale: "3120 mm",
      nombreEssieux: "2",
      classeEmission: "Euro 6",
      poidsTotal: "3500 kg",
      equipements: [
        "ABS",
        "ESP (programme de stabilité électronique)",
        "Climatisation",
        "Verrouillage centralisé",
        "Filtre à particules",
        "Garantie véhicule d’occasion",
      ],
    },
  },

  {
    id: "caravane-imgm",
    title: "SUNLIGHT T 60 D'OCCASION",
    price: "11000 €",
    image:
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.07.jpeg",
    gallery: [
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.45.49 (3).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.07.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.11 (1).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.11 (2).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.11 (3).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.11.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.12.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.13 (1).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.13.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.14 (1).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.14 (2).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.14.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.15.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.16 (1).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.16 (2).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.16.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.19.jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.20 (1).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.20 (2).jpeg",
      "/images/caravane/imgm/WhatsApp Image 2026-05-16 at 06.46.20.jpeg",
    ],
    description:
      "Ce camping-car est en excellent état et offre un niveau de confort élevé pour les voyages en famille ou en couple. Il dispose de lits simples à l’arrière ainsi qu’un coin repas central pouvant accueillir jusqu’à 4 personnes.\n\nL’espace intérieur comprend une cuisine entièrement équipée avec évier, plaque de cuisson et réfrigérateur, ainsi qu’une salle de bain avec douche séparée.\n\nLe véhicule dispose d’un garage avec portes latérales, d’une penderie et de nombreux équipements de confort et de sécurité.\n\nParmi les équipements, on retrouve la climatisation moteur, le régulateur de vitesse, une télévision à écran plat, un panneau solaire, une suspension pneumatique, une caméra de recul, un store occultant dans la cabine conducteur, une moustiquaire de porte, un porte-vélos, un auvent, un lanterneau, un toit ouvrant et un marchepied électrique.\n\nIl est également équipé de la radio, de l’ABS, de l’airbag, et dispose d’une vignette écologique.\n\nLe poids à vide est de 2 795 kg selon la carte grise, avec 4 places homologuées. Les pneus sont valables jusqu’en 2022. Le véhicule bénéficie d’un contrôle technique et d’un contrôle des émissions récents ainsi que d’une garantie d’un an.",
    features: [
      "Design moderne",
      "Cuisine équipée",
      "Espace optimisé",
      "Facile à tracter",
    ],
    category: "caravane",
    specs: {
      kilometrage: "38 460 km",
      puissance: "96 kW (130,52 ch)",
      nombreCouchages: "2",
      carburant: "Diesel",
      typeTransmission: "Mécanique",
      couleur: "Blanc",
      premiereImmatriculation: "07/2017",
      longueurTotale: "6931 mm",
      largeurTotale: "2325 mm",
      hauteurTotale: "2905 mm",
      poidsTotal: "3495 kg",
      equipements: ["ABS", "Climatisation", "Salle de bain"],
    },
  },
  {
    id: "remorque-imga",
    title:
      "Remorque cargo Doñana avec couvercle métallique et porte coulissante, 1200 x 1020 x 440 mm | 300 kg",
    price: "700 €",
    image: "/images/remorque/imga/asd.jpeg",
    gallery: [
      "/images/remorque/imga/WhatsApp Image 2026-05-16 at 06.49.12.jpeg",

      "/images/remorque/imga/WhatsApp Image 2026-05-16 at 06.49.13.jpeg",
      "/images/remorque/imga/WhatsApp Image 2026-05-16 at 06.49.13 (1).jpeg",
      "/images/remorque/imga/WhatsApp Image 2026-05-16 at 06.49.13 (2).jpeg",
    ],
    description:
      "Solution simple, sûre et propre pour le transport d’animaux de compagnie. Cette remorque de 1200 mm est équipée d’un essieu de 300 kg et d’une porte coulissante à barreaux, spécialement conçue pour le transport de chiens. Ses roues de 10 pouces permettent une circulation facile sur les chemins de terre. Le couvercle métallique intègre une galerie de toit pour le transport de marchandises.",
    features: [
      "Porte coulissante à barreaux",
      "Adaptée au transport de chiens",
      "Roues 10 pouces adaptées aux chemins de terre",
      "Couvercle métallique avec galerie de toit",
      "Roue de secours incluse",
      "Galvanisation à chaud pour réduire l’oxydation",
      "Entretien et nettoyage faciles",
      "Double essieu renforcé",
      "Châssis galvanisé à chaud",
      "Ridelles amovibles",
      "Système d'arrimage intégré",
    ],
    options: [
      "Revêtement en polyester",
      "Revêtement métallique",
      "Roue jockey",
    ],
    category: "caravane",
    specs: {
      dimensions: "2100 x 1385 mm",
      box_dimensions: "1200 x 1020 x 440 mm",
      mma: "300 kg",
      tare: "130 kg",
      axle: "1 axe / 300 kg",
    },
  },
  {
    id: "remorque-imgb",
    title: "Remorque plateau porte-voiture surbaissé - Modèle Apex B",
    price: "530 €",
    image:
       "/images/remorque/imgb/WhatsApp Image 2026-05-16 at 06.46.23 (1).jpeg",
    gallery: [
      "/images/remorque/imgb/WhatsApp Image 2026-05-16 at 06.46.23 (1).jpeg",
      "/images/remorque/imgb/WhatsApp Image 2026-05-16 at 06.46.23 (2).jpeg",
      "/images/remorque/imgb/WhatsApp Image 2026-05-16 at 06.46.23 (3).jpeg",
    ],
    description:
      "Idéale pour le transport de véhicules de sport ou de collection, cette remorque plateau porte-voiture surbaissée offre un angle de chargement très faible. Son châssis soudé robuste et galvanisé à chaud garantit une rigidité maximale et une tenue de route optimale.",
    features: [
      "Plateau basculant assisté",
      "Rampes robustes",
      "Treuil manuel inclus",
      "Anneaux d'arrimage solides",
    ],
    category: "caravane",
    specs: {
      dimensions: "2100 x 1385 mm",
      box_dimensions: "1200 x 1020 x 440 mm",
      mma: "300 kg",
      tare: "130 kg",
      axle: "1 axe / 300 kg",
      wheels: "4.50-10 pouces",
      material: "Galvanisé",
      brake: "Non",
    },
  },
  {
    id: "remorque-imgc",
    title: "Remorque benne hydraulique tri-benne - Modèle Cargo ",
    price: "1500 €",
    image:
      "/images/remorque/imgc/WhatsApp Image 2026-05-16 at 06.46.22 (1).jpeg",
    gallery: [
      "/images/remorque/imgc/WhatsApp Image 2026-05-16 at 06.46.22 (1).jpeg",
      "/images/remorque/imgc/WhatsApp Image 2026-05-16 at 06.46.28 (1).jpeg",
      "/images/remorque/imgc/WhatsApp Image 2026-05-16 at 06.46.28 (2).jpeg",
    ],
    description:
      "Le partenaire idéal pour les travaux agricoles et de chantier. Cette remorque tri-benne dispose d'un système de basculement hydraulique électrique sur 3 côtés (arrière, gauche, droite), offrant une flexibilité de déchargement inégalée. Ses ridelles doubles en aluminium renforcé sont entièrement rabattables et amovibles, permettant de transformer la benne en un grand plateau plat en un clin d'œil.",
    features: [
      "Bennage hydraulique tri-directionnel",
      "Ridelles alu double paroi",
      "Télécommande filaire",
      "Châssis haute résistance",
    ],
    category: "caravane",
    specs: {
      dimensions: "3.20m × 1.80m × 0.35m",
      weight: "580 kg",
      payload: "1920 kg",
      material: "Acier galvanisé et Aluminium",
      status: "Neuf",
      colors: "Gris alu / Noir",
    },
  },
  {
    id: "remorque-imgd",
    title: "Remorque benne basculante manuelle renforcée - Modèle Boxer ",
    price: "1250 €",
    image: "/images/remorque/imgd/WhatsApp Image 2026-05-16 at 06.47.19.jpeg",
    gallery: [
      "/images/remorque/imgd/WhatsApp Image 2026-05-16 at 06.47.19.jpeg",
      "/images/remorque/imgd/WhatsApp Image 2026-05-16 at 06.47.16 (1).jpeg",
      "/images/remorque/imgd/WhatsApp Image 2026-05-16 at 06.47.19 (1).jpeg",
    ],
    description:
      "Robuste et maniable, la Boxer D est dotée d'une benne basculante manuelle avec assistance par ressort à gaz. Conçue pour un usage semi-professionnel, elle convient idéalement aux travaux de jardinage, au transport de bois de chauffage ou de terre. Son essieu simple Al-Ko de haute qualité assure un amorti doux et une stabilité optimale.",
    features: [
      "Benne basculante assistée",
      "Essieu Al-Ko haut de gamme",
      "Roue jockey incluse",
      "Ridelle arrière ouvrante",
    ],
    category: "caravane",
    specs: {
      dimensions: "2.50m × 1.30m × 0.40m",
      weight: "240 kg",
      payload: "1010 kg",
      material: "Tôle galvanisée renforcée",
      status: "Neuf",
      colors: "Gris métallisé",
    },
  },
  {
    id: "remorque-imge",
    title: "Remorque fourgon fermée étanche - Modèle Box ",
    price: "450 €",
    image: "/images/remorque/imge/WhatsApp Image 2026-05-16 at 06.46.29.jpeg",
    gallery: [
      "/images/remorque/imge/WhatsApp Image 2026-05-16 at 06.46.29.jpeg",
      "/images/remorque/imge/WhatsApp Image 2026-05-16 at 06.46.28 (3).jpeg",
      "/images/remorque/imge/WhatsApp Image 2026-05-16 at 06.46.29 (1).jpeg",
    ],
    description:
      "Sécurisez vos transports grâce à cette remorque fourgon fermée. Équipée de panneaux composite bois-plastique de haute densité et d'un toit étanche en polyester, elle protège vos marchandises de la poussière, de l'humidité et du vol. Idéale pour le transport de meubles lors de déménagements, le matériel événementiel ou les livraisons de marchandises précieuses.",
    features: [
      "Fourgon fermé verrouillable",
      "Panneaux ultra-résistants",
      "Double porte arrière",
      "Sol antidérapant",
    ],
    category: "caravane",
    specs: {
      dimensions: "3.00m × 1.55m × 1.80m",
      weight: "450 kg",
      payload: "1550 kg",
      material: "Bois composite / Polyester",
      status: "Neuf",
      colors: "Blanc / Gris anthracite",
    },
  },
  {
    id: "remorque-imgf",
    title: "Remorque utilitaire double essieu bâchée - Modèle Carrier ",
    price: "550 €",
    image: "/images/remorque/imgf/WhatsApp Image 2026-05-16 at 06.46.46.jpeg",
    gallery: [
      "/images/remorque/imgf/WhatsApp Image 2026-05-16 at 06.46.46.jpeg",
      "/images/remorque/imgf/WhatsApp Image 2026-05-16 at 06.46.45 (1).jpeg",
      "/images/remorque/imgf/WhatsApp Image 2026-05-16 at 06.46.45 (2).jpeg",
      "/images/remorque/imgf/WhatsApp Image 2026-05-16 at 06.46.46 (1).jpeg",
      "/images/remorque/imgf/WhatsApp Image 2026-05-16 at 06.46.46 (2).jpeg",
    ],
    description:
      "Cette remorque polyvalente comprend une armature métallique et une bâche haute densité résistante aux déchirures. Son double essieu confère une excellente tenue de route sur tous les chemins. Idéale pour les artisans, déménageurs ou particuliers souhaitant protéger leur chargement tout en conservant la facilité de chargement d'un modèle ouvert.",
    features: [
      "Bâche amovible imperméable",
      "Double essieu suspendu",
      "Ridelles rabattables",
      "Hauteur utile de 1,60m",
    ],
    category: "caravane",
    specs: {
      dimensions: "2.60m × 1.40m × 1.60m",
      weight: "360 kg",
      payload: "1140 kg",
      material: "Acier galvanisé et toile PVC",
      status: "Neuf",
      colors: "Bleu / Gris",
    },
  },
  {
    id: "remorque-imgg",
    title: "Remorque plateau multi-usage légère - Modèle Trail G",
    price: "1190 €",
    image: "/images/remorque/imgg/WhatsApp Image 2026-05-16 at 06.47.32.jpeg",
    gallery: [
      "/images/remorque/imgg/WhatsApp Image 2026-05-16 at 06.47.32.jpeg",
      "/images/remorque/imgg/WhatsApp Image 2026-05-16 at 06.47.32 (1).jpeg",
      "/images/remorque/imgg/WhatsApp Image 2026-05-16 at 06.47.32 (2).jpeg",
    ],
    description:
      "La remorque la plus polyvalente pour un usage quotidien. Légère et robuste, elle se tracte très facilement, même par de petites citadines. Son plancher en bois marin antidérapant et ses ridelles latérales en acier nervuré permettent de tout transporter de façon sécurisée. Ridelle arrière rabattable pour faciliter le chargement.",
    features: [
      "Légère et maniable",
      "Plancher en bois marin antidérapant",
      "Garde-boue antichoc",
      "Éclairage LED intégré",
    ],
    category: "caravane",
    specs: {
      dimensions: "2.00m × 1.15m × 0.35m",
      weight: "140 kg",
      payload: "610 kg",
      material: "Acier zingué et contreplaqué",
      status: "Neuf",
      colors: "Gris métallisé",
    },
  },
  {
    id: "remorque-imgh",
    title: "Remorque benne hydraulique simple essieu - Modèle Dumper H",
    price: "2400 €",
    image: "/images/remorque/imgh/WhatsApp Image 2026-05-16 at 06.47.00.jpeg",
    gallery: [
      "/images/remorque/imgh/WhatsApp Image 2026-05-16 at 06.47.00.jpeg",
      "/images/remorque/imgh/WhatsApp Image 2026-05-16 at 06.47.00 (1).jpeg",
    ],
    description:
      "Remorque de bennage professionnel équipée d'un vérin hydraulique commandé par pompe manuelle haut de gamme. Idéale pour transporter et décharger du sable, des graviers ou des déchets verts sans effort physique. Son essieu simple de 1350 kg lui confère une grande maniabilité dans les espaces restreints.",
    features: [
      "Bennage hydraulique manuel",
      "Essieu robuste 1350 kg",
      "Ridelles amovibles",
      "Châssis robuste soudé",
    ],
    category: "caravane",
    specs: {
      dimensions: "2.60m × 1.50m × 0.35m",
      weight: "320 kg",
      payload: "1030 kg",
      material: "Acier galvanisé",
      status: "Neuf",
      colors: "Gris",
    },
  },
  {
    id: "remorque-imgi",
    title: "Remorque porte-engins renforcée à rampes - Modèle Force I",
    price: "3900 €",
    image: "/images/remorque/imgi/WhatsApp Image 2026-05-16 at 06.47.46.jpeg",
    gallery: [
      "/images/remorque/imgi/WhatsApp Image 2026-05-16 at 06.47.46.jpeg",
      "/images/remorque/imgi/WhatsApp Image 2026-05-16 at 06.47.45 (1).jpeg",
      "/images/remorque/imgi/WhatsApp Image 2026-05-16 at 06.47.46 (1).jpeg",
      "/images/remorque/imgi/WhatsApp Image 2026-05-16 at 06.47.46 (2).jpeg",
      "/images/remorque/imgi/WhatsApp Image 2026-05-16 at 06.47.46 (3).jpeg",
    ],
    description:
      "Spécialement conçue pour le transport de mini-pelles, rouleaux compresseurs ou engins de chantier lourds. Dotée d'un seuil de chargement ultra-bas et de rampes arrière en acier antidérapantes. Son châssis intégralement mécano-soudé offre une résistance extrême à la torsion.",
    features: [
      "Rampes d'accès robustes réglables",
      "Châssis mécano-soudé renforcé",
      "Garde-boue en tôle larmée",
      "Butée d'arrêt réglable",
    ],
    category: "caravane",
    specs: {
      dimensions: "3.50m × 1.70m",
      weight: "680 kg",
      payload: "2820 kg",
      material: "Acier mécano-soudé galvanisé",
      status: "Neuf",
      colors: "Gris foncé",
    },
  },
  {
    id: "remorque-imgj",
    title: "Remorque plateau ridelles aluminium - Modèle Swift J",
    price: "1750 €",
    image:
    "/images/remorque/imgj/WhatsApp Image 2026-05-16 at 06.48.43.jpeg",
    gallery: [
      "/images/remorque/imgj/WhatsApp Image 2026-05-16 at 06.48.30 (2).jpeg",
      "/images/remorque/imgj/WhatsApp Image 2026-05-16 at 06.48.42 (1).jpeg",
      "/images/remorque/imgj/WhatsApp Image 2026-05-16 at 06.48.43.jpeg",
      "/images/remorque/imgj/WhatsApp Image 2026-05-16 at 06.48.43 (1).jpeg",
      "/images/remorque/imgj/WhatsApp Image 2026-05-16 at 06.48.43 (2).jpeg",
    ],
    description:
      "Alliant légèreté et solidité, le modèle Swift J dispose de ridelles élégantes en aluminium anodisé. Son double essieu lui assure un comportement stable et sans sauts sur la route. Toutes les ridelles sont rabattables et amovibles, facilitant grandement le chargement latéral de palettes ou d'objets encombrants.",
    features: [
      "Ridelles en aluminium anodisé",
      "Toutes les ridelles rabattables",
      "Double essieu sans entretien",
      "Anneaux de fixation encastrés",
    ],
    category: "caravane",
    specs: {
      dimensions: "2.80m × 1.45m × 0.35m",
      weight: "295 kg",
      payload: "1205 kg",
      material: "Aluminium et Acier",
      status: "Neuf",
      colors: "Gris alu",
    },
  },
  {
    id: "remorque-imgk",
    title:
      "Remorque utilitaire multi-ridelles avec rehausses grillage - Modèle Green K",
    price: "1650 €",
    image: "/images/remorque/imgk/WhatsApp Image 2026-05-16 at 06.47.58.jpeg",
    gallery: [
      "/images/remorque/imgk/WhatsApp Image 2026-05-16 at 06.47.58.jpeg",
      "/images/remorque/imgk/WhatsApp Image 2026-05-16 at 06.47.57 (1).jpeg",
      "/images/remorque/imgk/WhatsApp Image 2026-05-16 at 06.47.58 (1).jpeg",
    ],
    description:
      "Le choix privilégié des élagueurs et des paysagistes. Équipée de rehausses grillagées robustes de 60 cm, elle permet de transporter un grand volume de branches, feuilles, gazon ou de déchets légers en toute sécurité. Son châssis en acier galvanisé renforcé lui garantit une longévité exceptionnelle sous haute sollicitation.",
    features: [
      "Rehausses grillagées de 60cm",
      "Double ridelle arrière ouvrante",
      "Haute capacité volumétrique",
      "Structure entièrement protégée",
    ],
    category: "caravane",
    specs: {
      dimensions: "2.60m × 1.35m × 0.95m",
      weight: "270 kg",
      payload: "980 kg",
      material: "Acier galvanisé",
      status: "Neuf",
      colors: "Gris zinc",
    },
  },
  {
    id: "remorque-imgl",
    title: "Remorque plateau basculant léger pour quads - Modèle Quad L",
    price: "1450 €",
    image:
    "/images/remorque/imgl/WhatsApp Image 2026-05-16 at 06.48.12 (2).jpeg",
    gallery: [
      "/images/remorque/imgl/WhatsApp Image 2026-05-16 at 06.47.58 (2).jpeg",
      "/images/remorque/imgl/WhatsApp Image 2026-05-16 at 06.48.12 (1).jpeg",
      "/images/remorque/imgl/WhatsApp Image 2026-05-16 at 06.48.12 (2).jpeg",
      "/images/remorque/imgl/WhatsApp Image 2026-05-16 at 06.48.30 (1).jpeg",
    ],
    description:
      "Spécialement conçue pour les amateurs de sports motorisés, la Quad L dispose d'un plateau basculant par gravité pour charger et décharger vos quads, motos ou petits engins de loisirs sans aucune rampe. Son profil aérodynamique bas réduit la consommation de carburant de votre véhicule tracteur.",
    features: [
      "Plateau basculant par gravité",
      "Pas de rampes requises",
      "Profil bas et stable",
      "Plaque d'immatriculation amovible",
    ],
    category: "caravane",
    specs: {
      dimensions: "2.50m × 1.50m",
      weight: "190 kg",
      payload: "560 kg",
      material: "Acier et aluminium",
      status: "Neuf",
      colors: "Gris métallisé",
    },
  },
  {
    id: "remorque-imgm",
    title: "Remorque bagagère de loisirs compacte - Modèle Eco M",
    price: "750 €",
    image:
      "/images/remorque/imgm/WhatsApp Image 2026-05-16 at 06.49.03 (1).jpeg",
    gallery: [
      "/images/remorque/imgm/WhatsApp Image 2026-05-16 at 06.49.03 (1).jpeg",
      "/images/remorque/imgm/WhatsApp Image 2026-05-16 at 06.49.03 (2).jpeg",
    ],
    description:
      "Parfaite pour les départs en vacances, le camping ou les petits travaux domestiques. L'Eco M est compacte, extrêmement légère et facile à ranger verticalement dans un garage pour économiser de la place. Son capot amovible disponible en option permet de sécuriser vos bagages des intempéries.",
    features: [
      "Compacte et ultra-légère",
      "Possibilité de stockage vertical",
      "Bâche ou capot en option",
      "Facile à manœuvrer",
    ],
    category: "caravane",
    specs: {
      dimensions: "1.50m × 1.05m × 0.32m",
      weight: "85 kg",
      payload: "415 kg",
      material: "Tôle d'acier zingué",
      status: "Neuf",
      colors: "Gris",
    },
  },
  {
    id: "mobile-home-imga",
    title: "Mobil-home Prestige - Villa d'Azur",
    price: "13750 €",
    oldPrice: "14950 €",
    discount: "8%",
    image:
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.24.jpeg",
    gallery: [
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.24 (1).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.24 (2).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.24 (3).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.24 (4).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.24.jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.25 (1).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.25 (2).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.25 (3).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.25 (4).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.25 (5).jpeg",
      "/images/mobilehome/imga/WhatsApp Image 2026-05-18 at 16.27.25.jpeg",
    ],
    description:
      "Découvrez l'élégance ultime avec ce mobil-home spacieux doté d'une finition en bois noble, d'une grande terrasse intégrée et de baies vitrées inondant le salon de lumière naturelle. Conçu pour allier grand confort et modernité.",
    features: [
      "Châssis double essieu",
      "Isolation 4 saisons",
      "Cuisine américaine",
      "Double vitrage phonique",
    ],
    category: "mobile-home",
    specs: {
      area: "42 m²",
      energy: "A++",
      warranty: "10 Ans",
      capacity: "4-6 Personnes",
      status: "Neuf",
      colors: "Gris Anthracite & Bois",
    },
  },
  {
    id: "mobile-home-imgb",
    title: "Mobil-home Lodge - Horizon Sauvage",
    price: "11785 €",
    oldPrice: "12950 €",
    discount: "9%",
    image:
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.46 (1).jpeg",
    gallery: [
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.46 (1).jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.46 (2).jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.46 (3).jpeg",
      
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.47 (1).jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.47 (2).jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.47 (3).jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.47 (4).jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.47 (5).jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.47.jpeg",
      "/images/mobilehome/imgb/WhatsApp Image 2026-05-18 at 16.27.48.jpeg",
    ],
    description:
      "Conçu pour s'intégrer harmonieusement dans les environnements forestiers ou côtiers. Ses larges ouvertures et son style scandinave offrent un refuge chaleureux et luxueux pour toute la famille.",
    features: [
      "Bardage bois naturel",
      "Poêle à granulés possible",
      "Meubles intégrés en chêne",
      "Éclairage LED basse consommation",
    ],
    category: "mobile-home",
    specs: {
      area: "36 m²",
      energy: "A+",
      warranty: "8 Ans",
      capacity: "4 Personnes",
      status: "Neuf",
      colors: "Chêne Clair & Blanc",
    },
  },
  {
    id: "mobile-home-imgc",
    title: "Mobil-home Suite - Royal Comfort",
    price: "12555 €",
    oldPrice: "13950 €",
    discount: "10%",
    image:
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.11 (1).jpeg",
    gallery: [
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.11 (1).jpeg",
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.11 (2).jpeg",
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.11 (3).jpeg",
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.12 (1).jpeg",
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.12 (2).jpeg",
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.12 (3).jpeg",
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.12 (4).jpeg",
      "/images/mobilehome/imgc/WhatsApp Image 2026-05-18 at 16.28.12.jpeg",
    ],
    description:
      "L'excellence hôtelière chez vous. Ce modèle se distingue par sa suite parentale monumentale, sa salle de bain design avec douche italienne et ses finitions très haut de gamme pour des moments inoubliables.",
    features: [
      "Suite parentale XXL",
      "Douche à l'italienne",
      "Climatisation réversible",
      "Cuisine avec plan de travail en quartz",
    ],
    category: "mobile-home",
    specs: {
      area: "45 m²",
      energy: "A+++",
      warranty: "12 Ans",
      capacity: "2-4 Personnes",
      status: "Neuf",
      colors: "Marbre Blanc & Noir",
    },
  },
  {
    id: "mobile-home-imgd",
    title: "Mobil-home Family - Espace & Partage",
    price: "30315 €",
    oldPrice: "32950 €",
    discount: "8%",
    image:
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.06.jpeg",
    gallery: [
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.06 (1).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.06 (2).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.06.jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.07 (1).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.07 (2).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.07 (3).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.07 (4).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.07 (5).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.07.jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.08 (1).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.08 (2).jpeg",
      "/images/mobilehome/imgd/WhatsApp Image 2026-05-18 at 16.30.08.jpeg",
    ],
    description:
      "Le mobil-home familial idéal par excellence. Avec ses 3 chambres indépendantes et son salon central convivial, il offre à chaque membre de la famille son propre espace de confort et d'intimité.",
    features: [
      "3 chambres spacieuses",
      "Salon central panoramique",
      "Nombreux rangements astucieux",
      "Volets roulants dans les chambres",
    ],
    category: "mobile-home",
    specs: {
      area: "44 m²",
      energy: "A+",
      warranty: "10 Ans",
      capacity: "6-8 Personnes",
      status: "Neuf",
      colors: "Bleu Nuit & Blanc beige",
    },
  },
  {
    id: "mobile-home-imge",
    title: "Mobil-home Tiny - Cocon Nordique",
    price: "16325 €",
    oldPrice: "17950 €",
    discount: "9%",
    image:
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.36 (1).jpeg",
    gallery: [
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.36 (1).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.36 (2).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.36 (3).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.36 (4).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.36 (5).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.37 (1).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.37 (2).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.37 (3).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.37 (4).jpeg",
      "/images/mobilehome/imge/WhatsApp Image 2026-05-18 at 16.30.37.jpeg",
    ],
    description:
      "Un modèle ultra-compact mais ingénieux, optimisé pour offrir tout le confort d'un grand chez-soi dans un espace maîtrisé. Parfait pour les terrains intimistes ou les petits budgets exigeants.",
    features: [
      "Espace optimisé au millimètre",
      "Chauffage au sol ultra-fin",
      "Mobilier escamotable intelligent",
      "Grande verrière de toit",
    ],
    category: "mobile-home",
    specs: {
      area: "28 m²",
      energy: "A++",
      warranty: "10 Ans",
      capacity: "2 Personnes",
      status: "Neuf",
      colors: "Blanc Pur & Pin Nordique",
    },
  },
  {
    id: "mobile-home-imgf",
    title: "Mobil-home Loft - Vue Panoramique",
    price: "26055 €",
    oldPrice: "28950 €",
    discount: "10%",
    image:
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.58 (1).jpeg",
    gallery: [
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.58 (1).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.58 (2).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.58 (3).jpeg",
      
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.59 (1).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.59 (2).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.59 (3).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.59 (4).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.59 (5).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.30.59.jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.31.00 (1).jpeg",
      "/images/mobilehome/imgf/WhatsApp Image 2026-05-18 at 16.31.00.jpeg",
    ],
    description:
      "Vivez en communion avec la nature grâce à sa façade entièrement vitrée. Le salon cathédrale sous plafond rampant offre une sensation d'espace et de liberté incomparable et unique.",
    features: [
      "Façade vitrée panoramique",
      "Plafond cathédrale",
      "Cuisine équipée premium",
      "Terrasse surélevée optionnelle",
    ],
    category: "mobile-home",
    specs: {
      area: "48 m²",
      energy: "A+++",
      warranty: "15 Ans",
      capacity: "4 Personnes",
      status: "Neuf",
      colors: "Gris Quartz & Bois Exotique",
    },
  },
  {
    id: "mobile-home-imgg",
    title: "Mobil-home Chalet - Tradition Bois",
    price: "17480 €",
    oldPrice: "19000 €",
    discount: "8%",
    image:
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.29.jpeg",
    gallery: [
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.29 (1).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.29 (2).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.29 (3).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.29 (4).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.29 (5).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.29.jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.30 (1).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.30 (2).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.30 (3).jpeg",
      "/images/mobilehome/imgg/WhatsApp Image 2026-05-18 at 16.31.30.jpeg",
    ],
    description:
      "L'authenticité du chalet de montagne alliée au design contemporain d'un mobil-home moderne. Son isolation thermique renforcée vous garantit un confort douillet en toute saison, même en hiver.",
    features: [
      "Isolation renforcée laine de roche",
      "Style chalet de montagne",
      "Cuisine rustique chic",
      "Radiateurs connectés",
    ],
    category: "mobile-home",
    specs: {
      area: "38 m²",
      energy: "A++",
      warranty: "10 Ans",
      capacity: "4-6 Personnes",
      status: "Neuf",
      colors: "Mélèze Naturel",
    },
  },
  {
    id: "mobile-home-imgh",
    title: "Mobil-home Urban - Studio Chic",
    price: "15982 €",
    oldPrice: "17580 €",
    discount: "9%",
    image:
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.37 (1).jpeg",
    gallery: [
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.37 (1).jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.37 (2).jpeg",
      
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.38 (1).jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.38 (2).jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.38 (3).jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.38 (4).jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.38 (5).jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.38 (6).jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.38.jpeg",
      "/images/mobilehome/imgh/WhatsApp Image 2026-05-18 at 16.32.39.jpeg",
    ],
    description:
      "Un design urbain et résolument moderne avec son bardage composite imitation métal et ses finitions intérieures épurées. L'habitat moderne nomade par excellence pour couple branché.",
    features: [
      "Bardage composite sans entretien",
      "Style industriel épuré",
      "Grand dressing intégré",
      "Espace bureau pour télétravail",
    ],
    category: "mobile-home",
    specs: {
      area: "34 m²",
      energy: "A+",
      warranty: "8 Ans",
      capacity: "2 Personnes",
      status: "Neuf",
      colors: "Gris Zinc & Métal Noir",
    },
  },
  {
    id: "mobile-home-imgi",
    title: "Mobil-home Oasis - Esprit Nature",
    price: "20241 €",
    oldPrice: "22490 €",
    discount: "10%",
    image:
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.37 (1).jpeg",
    gallery: [
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.37 (1).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.37 (2).jpeg",
     
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.38 (1).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.38 (2).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.38 (3).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.38 (4).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.38 (5).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.38.jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.39 (1).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.39 (2).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.39 (3).jpeg",
      "/images/mobilehome/imgi/WhatsApp Image 2026-05-18 at 16.34.39.jpeg",
    ],
    description:
      "Conçu comme une oasis de fraîcheur et de sérénité, ce modèle intègre des matériaux biosourcés et un système de ventilation naturelle double flux pour un bien-être optimal au quotidien.",
    features: [
      "Matériaux écologiques biosourcés",
      "Ventilation double flux intégrée",
      "Douche avec mitigeur thermostatique",
      "Terrasse ombragée",
    ],
    category: "mobile-home",
    specs: {
      area: "40 m²",
      energy: "A++",
      warranty: "12 Ans",
      capacity: "4 Personnes",
      status: "Neuf",
      colors: "Vert Sauge & Chêne Massif",
    },
  },
  {
    id: "mobile-home-imgj",
    title: "Mobil-home Exclusive - Villa Impériale",
    price: " 11270 €",
    oldPrice: "122500 €",
    discount: "8%",
    image:
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.31 (1).jpeg",
    gallery: [
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.30 (1).jpeg",
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.30 (2).jpeg",
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.30 (3).jpeg",
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.31 (1).jpeg",
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.31 (2).jpeg",
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.31 (3).jpeg",
      "/images/mobilehome/imgj/WhatsApp Image 2026-05-18 at 16.35.31 (4).jpeg",
      
    ],
    description:
      "Le fleuron de notre gamme de mobil-homes. Une conception sur-mesure d'exception offrant un salon immense, deux salles de bains privatives et une autonomie énergétique remarquable.",
    features: [
      "Double salle de bains haut de gamme",
      "Autonomie solaire en option",
      "Cuisine en L avec îlot central",
      "Garantie constructeur étendue",
    ],
    category: "mobile-home",
    specs: {
      area: "52 m²",
      energy: "A+++",
      warranty: "15 Ans",
      capacity: "4-6 Personnes",
      status: "Neuf",
      colors: "Blanc Cendré & Noyer",
    },
  },
];
